/**
 * DGLOPA PLATFORM — SEMANTIC INTELLIGENCE FRAMEWORK
 * eventTypes.js — DT-008A (Semantic)
 *
 * Canonical event type string constants.
 * One file of truth — import from here, never hard-code strings.
 *
 * Organised by source domain. Naming convention: DOMAIN_VERB_NOUN.
 */

// ---- Receiving ----
export const RECEIVING_SESSION_STARTED    = 'RECEIVING_SESSION_STARTED';
export const RECEIVING_SESSION_COMPLETED  = 'RECEIVING_SESSION_COMPLETED';
export const RECEIVING_SESSION_CANCELLED  = 'RECEIVING_SESSION_CANCELLED';
export const RECEIVING_INVOICE_RECEIVED   = 'RECEIVING_INVOICE_RECEIVED';

// ---- Inventory ----
export const INVENTORY_LOT_CREATED        = 'INVENTORY_LOT_CREATED';
export const INVENTORY_LOT_EXPIRED        = 'INVENTORY_LOT_EXPIRED';
export const INVENTORY_LOT_NEAR_EXPIRY    = 'INVENTORY_LOT_NEAR_EXPIRY';
export const INVENTORY_STOCK_OUT          = 'INVENTORY_STOCK_OUT';
export const INVENTORY_LOW_STOCK          = 'INVENTORY_LOW_STOCK';

// ---- Supplier ----
export const SUPPLIER_CREATED             = 'SUPPLIER_CREATED';
export const SUPPLIER_ARCHIVED            = 'SUPPLIER_ARCHIVED';
export const SUPPLIER_RESTORED            = 'SUPPLIER_RESTORED';
export const SUPPLIER_MERGED              = 'SUPPLIER_MERGED';
export const SUPPLIER_UPDATED             = 'SUPPLIER_UPDATED';
export const SUPPLIER_FIRST_PURCHASE      = 'SUPPLIER_FIRST_PURCHASE';
export const SUPPLIER_PURCHASE_RECORDED   = 'SUPPLIER_PURCHASE_RECORDED';

// ---- Demand ----
export const DEMAND_CAPTURED              = 'DEMAND_CAPTURED';
export const DEMAND_RESOLVED              = 'DEMAND_RESOLVED';
export const DEMAND_IGNORED               = 'DEMAND_IGNORED';
export const DEMAND_REPEAT_DETECTED       = 'DEMAND_REPEAT_DETECTED';

// ---- Review ----
export const REVIEW_ITEM_RAISED           = 'REVIEW_ITEM_RAISED';
export const REVIEW_ITEM_RESOLVED         = 'REVIEW_ITEM_RESOLVED';
export const REVIEW_QUEUE_CLEARED         = 'REVIEW_QUEUE_CLEARED';

// ---- Migration ----
export const MIGRATION_IMPORT_COMMITTED   = 'MIGRATION_IMPORT_COMMITTED';
export const MIGRATION_IMPORT_FAILED      = 'MIGRATION_IMPORT_FAILED';

// ---- Synthetic Milestones ----
export const MILESTONE_PURCHASE_VALUE     = 'MILESTONE_PURCHASE_VALUE';
export const MILESTONE_SESSION_COUNT      = 'MILESTONE_SESSION_COUNT';
export const MILESTONE_PRODUCT_COUNT      = 'MILESTONE_PRODUCT_COUNT';
export const MILESTONE_RELATIONSHIP       = 'MILESTONE_RELATIONSHIP';
export const MILESTONE_DEMAND_THRESHOLD   = 'MILESTONE_DEMAND_THRESHOLD';
export const MILESTONE_REVIEW_CLEARED     = 'MILESTONE_REVIEW_CLEARED';

// ---- All types array (for validation) ----
export const ALL_EVENT_TYPES = Object.freeze([
  RECEIVING_SESSION_STARTED, RECEIVING_SESSION_COMPLETED, RECEIVING_SESSION_CANCELLED,
  RECEIVING_INVOICE_RECEIVED,
  INVENTORY_LOT_CREATED, INVENTORY_LOT_EXPIRED, INVENTORY_LOT_NEAR_EXPIRY,
  INVENTORY_STOCK_OUT, INVENTORY_LOW_STOCK,
  SUPPLIER_CREATED, SUPPLIER_ARCHIVED, SUPPLIER_RESTORED, SUPPLIER_MERGED,
  SUPPLIER_UPDATED, SUPPLIER_FIRST_PURCHASE, SUPPLIER_PURCHASE_RECORDED,
  DEMAND_CAPTURED, DEMAND_RESOLVED, DEMAND_IGNORED, DEMAND_REPEAT_DETECTED,
  REVIEW_ITEM_RAISED, REVIEW_ITEM_RESOLVED, REVIEW_QUEUE_CLEARED,
  MIGRATION_IMPORT_COMMITTED, MIGRATION_IMPORT_FAILED,
  MILESTONE_PURCHASE_VALUE, MILESTONE_SESSION_COUNT, MILESTONE_PRODUCT_COUNT,
  MILESTONE_RELATIONSHIP, MILESTONE_DEMAND_THRESHOLD, MILESTONE_REVIEW_CLEARED,
]);
